"""Canonical Pydantic event schema.

Public surface:

* :data:`EventKind` — the literal-type enum of all event-envelope kinds.
* All payload classes in :mod:`hutch.schema.payloads`.
* All concrete Event classes in :mod:`hutch.schema.events`.
* :data:`AnyEvent` / :data:`EVENT_ADAPTER` — discriminated-union dispatcher.
"""

from __future__ import annotations

from hutch.schema.events import (
    EVENT_ADAPTER,
    EVENT_CLASSES,
    AnyEvent,
    ArchiveSnapshotEvent,
    ArtifactEvent,
    ClaimEvent,
    DescriptorEvent,
    EvidenceEvent,
    FitnessEvent,
    IndividualEvent,
    LineageEdgeEvent,
    MigrationEvent,
    OperatorEvent,
    ParetoSnapshotEvent,
    ReviewEvent,
    RunEndEvent,
    RunStartEvent,
    RunUpdateEvent,
    SelfModEvent,
    SteeringCommandEvent,
    StreamEventEvent,
    TreeExpansionEvent,
)
from hutch.schema.payloads import (
    ArchiveSnapshotPayload,
    ArtifactPayload,
    ClaimPayload,
    DescriptorPayload,
    EvidencePayload,
    FitnessPayload,
    IndividualPayload,
    LineageEdgePayload,
    MigrationPayload,
    OperatorPayload,
    ParetoSnapshotPayload,
    ReviewPayload,
    RunEndPayload,
    RunStartPayload,
    RunUpdatePayload,
    SelfModPayload,
    SteeringCommandPayload,
    StreamEventPayload,
    TreeExpansionPayload,
)
from hutch.schema.types import (
    ALL_KINDS,
    ArtifactKind,
    DescriptorArchiveKind,
    EvaluatorKind,
    EventKind,
    EvidenceStance,
    IndividualKind,
    OperatorKind,
    PopulationKind,
    RunStatus,
    ScoreDirection,
    SelfModVerdict,
    SteeringActor,
    SteeringCommandKind,
)

__all__ = [
    "ALL_KINDS",
    "EVENT_ADAPTER",
    "EVENT_CLASSES",
    "AnyEvent",
    "ArchiveSnapshotEvent",
    "ArchiveSnapshotPayload",
    "ArtifactEvent",
    "ArtifactKind",
    "ArtifactPayload",
    "ClaimEvent",
    "ClaimPayload",
    "DescriptorArchiveKind",
    "DescriptorEvent",
    "DescriptorPayload",
    "EvaluatorKind",
    "EventKind",
    "EvidenceEvent",
    "EvidencePayload",
    "EvidenceStance",
    "FitnessEvent",
    "FitnessPayload",
    "IndividualEvent",
    "IndividualKind",
    "IndividualPayload",
    "LineageEdgeEvent",
    "LineageEdgePayload",
    "MigrationEvent",
    "MigrationPayload",
    "OperatorEvent",
    "OperatorKind",
    "OperatorPayload",
    "ParetoSnapshotEvent",
    "ParetoSnapshotPayload",
    "PopulationKind",
    "ReviewEvent",
    "ReviewPayload",
    "RunEndEvent",
    "RunEndPayload",
    "RunStartEvent",
    "RunStartPayload",
    "RunStatus",
    "RunUpdateEvent",
    "RunUpdatePayload",
    "ScoreDirection",
    "SelfModEvent",
    "SelfModPayload",
    "SelfModVerdict",
    "SteeringActor",
    "SteeringCommandEvent",
    "SteeringCommandKind",
    "SteeringCommandPayload",
    "StreamEventEvent",
    "StreamEventPayload",
    "TreeExpansionEvent",
    "TreeExpansionPayload",
]
